apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: changens
  name: changens
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: changedeploymentname
  namespace: changens
spec:
  selector:
    matchLabels:
      app: changedeploymentname
  replicas: 3
  template:
    metadata:
      labels:
        app: changedeploymentname
    spec:
      containers:
      - name: changedeploymentname
        image: changeimage
        imagePullPolicy: Always
        ports:
        - name: changedeploymentname
          containerPort: changeport
          protocol: TCP
      imagePullSecrets:
      - name: ocirloginsecret
      nodeSelector:
        usage: weblogic

---
apiVersion: v1
kind: Service
metadata:
  name: changeservice
  namespace: changens
  labels:
    app: changedeploymentname
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
spec:
  type: ClusterIP
  ports:
  - port: changeport
  selector:
    app: changedeploymentname
